<?php
namespace Database\Seeders;
use App\Post;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $posts = array(
            array(
                "title" => "[ Info Futsal HMIF ] HMIF VS DKV",
                "slug" => "info-futsal-hmif-hmif-vs-dkv",
                "content" => "Datang,Dukung dan Ramaikan Futsal HMIF \" Berikan penampilan terbaik dan selalu berusaha keras disetiap pertandingan \"\r\n<br>\r\n#HMIFItenas\r\n<br>#ItenasBandung\r\n<br>#kampusoranges",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-03-24_TIME_10-23-28-PM_28153701_181956582424466_5428722453213872128_n.jpg",
            ),
            array(
                "title" => "[ Info Basket HMIF ] HMIF VS HMPL",
                "slug" => "info-basket-hmif-hmif-vs-hmpl",
                "content" => "Datang,Dukung dan Ramaikan Basket HMIF.\r\nHARI INI !!!!! Di Lapbas Itenas jam 17.00 .<br>&nbsp;#HMIFItenas\r\n<br>#ItenasBandung<br>&nbsp;#kampusoranges",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-03-24_TIME_10-27-08-PM_28152602_230550657491289_8763439867620229120_n.jpg",
            ),
            array(
                "title" => "[ Info Basket HMIF ]HMIF VS HMTK",
                "slug" => "info-basket-hmif-hmif-vs-hmtk",
                "content" => "Datang,Dukung dan Ramaikan Basket HMIF.\r\nHARI INI !!!!! Di Lapbas Itenas jam 19.00\r\nTunjukan Kemenanganmu HMIF!!!!<br>&nbsp;#HMIFItenas\r\n<br>#ItenasBandung<br>&nbsp;#kampusoranges",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-03-24_TIME_10-27-41-PM_28434706_1788293574556273_2597970947927441408_n.jpg",
            ),
            array(
                "title" => "\"Graduation Night Party\"",
                "slug" => "graduation-night-party",
                "content" => " HMIF ITENAS MEMPERSEMBAHKAN\r\n. \"Graduation Night Party\"\r\n\r\nRabu, 07 Maret 2018\r\n????06.30 - Selesai\r\n???? Halaman Gedung 2 ITENAS\r\n\r\nYuk Datang dan Ramaikan\r\n.\r\n\r\n#HMIFItenas\r\n#ItenasBandung\r\n#KampusOrange",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-03-24_TIME_10-28-18-PM_28764582_103307123839625_7241241378460532736_n.jpg",
            ),
            array(
                "title" => "Graduation Night Party",
                "slug" => "graduation-night-party",
                "content" => "\"Graduation Night Party\"\r\n<br>\r\nRabu, 07 Maret 2018 <br>18.30 - Selesai <br>&nbsp;Halaman Gedung 2 ITENAS\r\n\r\n<br>Yuk Datang dan Ramaikan\r\n.\r\n\r\n<br>#HMIFItenas<br>&nbsp;#ItenasBandung<br>&nbsp;#KampusOrange",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-03-24_TIME_10-30-16-PM_28764420_2116489611916112_6461301435203059712_n.jpg",
            ),
            array(
                "title" => "DIESNATALIS 13th",
                "slug" => "diesnatalis-13th",
                "content" => " H-1 MENUJU SIMBOLIS DIES NATALIS HMIF-13 !!!!!!!",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-03-24_TIME_10-31-13-PM_28434927_1844839669141893_8730140582447415296_n.jpg",
            ),
            array(
                "title" => "SELAMAT HARI RAYA NYEPI TAHUN BARU SAKA  1940",
                "slug" => "selamat-hari-raya-nyepi-tahun-baru-saka-1940",
                "content" => " Dalam kesunyian kan kau dapati makna kehidupan. Dalam kesepian kan kau rasakan kehadiran-Nya. Tuhan bersama orang-orang yang selalu ingat akan penciptanya. Selamat Hari Raya Nyepi.",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-03-24_TIME_10-32-17-PM_28765095_2022567018066318_3389399482025115648_n.jpg",
            ),
            array(
                "title" => "MARI MENGAJI !",
                "slug" => "mari-mengaji",
                "content" => "“Barang siapa yang membaca satu huruf dari Al-Qur’an maka baginya kebaikan sepuluh kali lipat, aku tidak mengatakan Alif Lam Mim satu huruf akan tetapi Alif satu huruf, Lam satu huruf, Mim satu huruf.” (Shahih HR.Tirmidzi)\r\n\r\nOleh karena itu, Mari Mengaji ! .<br><br>&nbsp;-Div. Kerohanian HMIF-",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-03-24_TIME_10-32-43-PM_29087437_1981590715493343_5117765498133544960_n.jpg",
            ),
            array(
                "title" => "HELLO GUYS! GOOD NEWS nih. Kami punya akun email dan website baru. Email : HMIF@ITENAS.AC.ID Website : HMIF.ITENAS.AC.ID",
                "slug" => "hello-guys-good-news-nih-kami-punya-akun-email-dan-website-baru-email-hmifitenasacid-website-hmifitenasacid",
                "content" => "HELLO GUYS!\r\nGOOD NEWS nih.\r\n<br>Kami punya akun email dan website baru.\r\n<br>Email : HMIF@ITENAS.AC.ID\r\n<br>Website : HMIF.ITENAS.AC.ID\r\n\r\nLET'S GO HUNT dudududududu.\r\n<br>LET'S GO HUNT dudududududu.\r\n\r\n<br>#hmifitenas\r\n<br>#itenas<br>&nbsp;#website\r\n<br>#kampusoranges",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-04-02_TIME_07-45-54-PM_29403902_381925838948403_3063793346980872192_n.jpg",
            ),
            array(
                "title" => "CALLING FOR TENANTS",
                "slug" => "calling-for-tenants",
                "content" => "CALLING FOR TENANTS <br>Haii haii\r\nKami dari tim Bazaar ITIC 2018 membuka kesempatan buat kalian yang ingin unjuk bisnis dalam rangka Itenas Technology and Innovation Championship 2018. <br>\r\nPenasaran gimana caranya? Langsung aja yukk kepoin info dan cara daftarnya ke contact person yang tercantum di poster  #ITIC2018\r\n#Technovature\r\n#ItenasTechnologyAndInnovationChampionship",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-04-02_TIME_07-46-53-PM_29737424_2150911421852370_1581491874185609216_n.jpg",
            ),
            array(
                "title" => "Lomba Robot & Drone #Technovature!",
                "slug" => "lomba-robot-drone-technovature",
                "content" => "Lomba Robot &amp; Drone #Technovature!\r\n\r\n<br>Berbagai lomba robot dengan kategori Umum:\r\n<br>- Applicative Robot (umum)\r\n<br>- Line Follower Analog (umum)\r\n<br>- Drone Racing (umum)\r\n<br>\r\nLomba Robot Internasional\r\nThe 3rd FSI-All Indonesia &amp; World Robot-Sumo Tournament 2018- Autonomous Category (Umum)\r\n\r\nDayang Sumbi Innovation Award (Mahasiswa Itenas) *Pendaftaran 1-31 Maret 2018\r\n\r\n<br>Info:\r\n087822887474 (Fajri)\r\n<br>IG: @itic2018\r\nWeb: <a target=\"_blank\" rel=\"nofollow\" href=\"http://www.itic-itenas.com\">www.itic-itenas.com</a>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-04-02_TIME_07-47-43-PM_29401731_360373051148858_772632576094371840_n.jpg",
            ),
            array(
                "title" => "Selamat menjalankan Ujian Tengah Semester",
                "slug" => "selamat-menjalankan-ujian-tengah-semester",
                "content" => "Jangan lupa belajar dan berdoa",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-04-02_TIME_07-50-17-PM_29416333_155927261767519_7584541047892475904_n.jpg",
            ),
            array(
                "title" => "REHAT SEJENAK [EPISODE 1]",
                "slug" => "rehat-sejenak-episode-1",
                "content" => "Penat dengan apa yang kalian perbuat di UTS ?\r\n<br>Bosan dengan malam minggu yang hampa ?\r\n\r\n<br>Jangan Khawatir karena malam minggu nanti\r\nRehat Sejenak datang kembali untuk menghibur kalian.\r\nBuat Kalian Anggota HMIF bisa ikut meramaikan \r\nAcara liliwetan dan makan sepuasnnya.\r\n<br>\r\nHari/Tanggal : Sabtu, 7 April 2018<br>Tempat : Halaman belakang gedung 2, <br>Itenas\r\nPukul : 19.00 - Cape WIB\r\n\r\n<br>Jangan sampai kelewatan momen kebersamaanya ya. Apa lagi momen sama si doi.<br>&nbsp;PERINGATAN : Jangan Lupa bawa beras cukup 1 cup tapi jangan sampe bawa kabogoh batur\r\nariqbal_Baru tau makan bagian dari seni ):\r\nhmifitenasIya karena makan menciptakan keindahan di dalam lambung dan hati",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-04-06_TIME_06-01-13-PM_rehat.jpg",
            ),
            array(
                "title" => "Debat Calon Ketua Angkatan 2017",
                "slug" => "debat-calon-ketua-angkatan-2017",
                "content" => "Hari / tgl : Senin,  09 April 2018 \r\n<br>Pukul : 17.00 - Selesai \r\n<br>Tempat : Ruang 2301\r\n\r\n<br>Akan dilaksanakan Debat Calon Ketua Angkatan 2017 \r\n\r\n*Dresscode angkatan 2017 ( anggota Aktif HMIF )  memakai pakaian rapi dah sopan + Slayer himpunan\r\n\r\n* Anggota Pasif memakai Pakaian Rapi dan sopan. \r\n\r\nDiharapkan kepada seluruh rekan-rekan angkatan 2017 untuk datang dan hadir ..",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-04-08_TIME_08-30-41-PM_debatkaang2017.jpg",
            ),
            array(
                "title" => "TECHNOVACTURE 2018",
                "slug" => "technovacture-2018",
                "content" => "&nbsp;Kamu PELAJAR ? MAHASISWA? ATAU SIAPAPUN KAMU HOBI NGULIK ROBOT DAN DRONE?!! YUK IKUT LOMBA BERTARAF NASIONAL DIBAWAH INI :<br>Applicative Robot (Umum)<br>&nbsp;Line Follower Analog (Umum)<br>Drone Racing (Umum)<br><br>&nbsp;EITS GAMAU YG NASIONAL AJA? MAU KE JEPANG MEWAKILI INDONESIA ? BERARTI KAMU HARUS IKUT LOMBA INI DONG :<br>&nbsp;The 3rd FSI-All Indonesia &amp; World Robot-Sumo Tournament 2018- Autonomous Category (Umum)<br><br>Nah untuk kamu MAHASISWA ITENAS WAJIB BANGET ikut event dibawah ini : .????. Dayang sumbi Innovation Award .<br>&nbsp;Udah milih mau ikut yang mana? Tim nya sudah siap ? Yuk langsung daftar aja sebelum terlambat!! AWAS NYESEL LOH :D<br>.<br>*) Pendaftaran terakhir : 7 April 2018<br>.<br>Contact Person :<br>+6287822887474 (fajri)<br>+6289635257159 (Adi)<br>.<br>More info:<br>Facebook: ITIC 2018<br>Twitter: <a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/ITIC2018/\">@ITIC2018</a><br>Instagram: <a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/itic2018/\">@itic2018</a><br>Website: <a target=\"_blank\" rel=\"nofollow\" href=\"http://www.itic-itenas.com\">www.itic-itenas.com</a>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-04-09_TIME_09-55-46-PM_93425.jpg",
            ),
            array(
                "title" => "DILo Road To Campus - Digitalpreneur Virus",
                "slug" => "dilo-road-to-campus-digitalpreneur-virus",
                "content" => "<p>\r\n\r\nDILo (Digital Innovation Lounge) Bandung bersama Himpunan Mahasiswa Teknik Informatika ITENAS proudly present: \"DILo Road To Campus - Digitalpreneur Virus\"&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p><p>Tanggal:&nbsp; 18 April 2018&nbsp;</p><p>Jam:13.00 s/d selesai</p><p>Gedung Perpustakaan Lantai 3 Institut Teknologi Nasional (9301)&nbsp; Registation Free !!<br>Terbatas untuk 100 orang<br><br>Pendaftaran dengan cara mengirim:<br>Nama :<br>Nrp :<br>Jurusan : Kirim ke:<br>Line : dewisptrn<br>Hp : 08996908468<br><br>Dan harus meregistrasi pada link di bawah ini :<br><a target=\"_blank\" rel=\"nofollow\" href=\"http://bit.ly/dilobdgroadtocampusitenas\">http://bit.ly/dilobdgroadtocampusitenas</a><br><br>Sampai jumpa ya????<br>Salam DILo Bandung dan HMIF!<br>Perfect pleace for digital people!!<br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/dilo/\">#Dilo</a>&nbsp;<a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/dilobandung/\">#DiloBandung</a>&nbsp;<a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/diloindonesia/\">#DiloIndonesia</a><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/diloroadtocampus/\">#DiloRoadToCampus</a>&nbsp;<a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/digitalpreneurvirus/\">#DigitalpreneurVirus</a><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/itenas/\">#Itenas</a>&nbsp;<a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmif/\">#HMIF</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-04-14_TIME_09-16-49-PM_dilo.jpg",
            ),
            array(
                "title" => "Informatika 2017 mempersembahkan.",
                "slug" => "informatika-2017-mempersembahkan",
                "content" => "<p>\r\n\r\nMinggu,22 April 2018<br>05.00 P.M - Selesai<br>Student Center ITENAS<br><br>Kuy kita ramaikan malam keakraban 2017<br></p><p><br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-04-21_TIME_07-48-17-AM_makrab2017.jpg",
            ),
            array(
                "title" => "[BADMINTON COMPETITION]",
                "slug" => "badminton-competition",
                "content" => "<p>\r\n\r\nTelah hadir~<br>Kompetisi Badminton antar sesama Teknik Informatika Itenas.<br>Ayo daftar dan raih kemenanganmu.<br><br>Pendaftaran di mulai pada tanggal 20 - 29 April 2018<br><br>Daftarkan Sekarang Juga!!<br>Untuk seluruh angkatan Teknik Informatika<br>Bertempat di : GOR Prestasi (dekat Pusdai)<br><br>Biaya pendaftaran :<br>- Ganda Putra = 50K<br>- Ganda Campuran = 50K<br>- Tunggal Putra = 30K<br><br>Pendaftaran dan info lebih lanjut bisa menghubungi : *Fahmi Rabiul Karim<br>ID (line) : fahmirabiul<br>*Fachry Prayoga<br>ID (line) : fachry_prayoga\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-04-24_TIME_09-48-27-AM_badminton.jpg",
            ),
            array(
                "title" => "[Info Turnamen Futsal]",
                "slug" => "info-turnamen-futsal",
                "content" => "<p>\r\n\r\nDatang, dukung, dan ramaikan.<br>Hari ini! Di Lap. Futsal Itenas jam 18.15<br>Tunjukkan semangatmu dan kalahkan lawan-lawanmu HMIF!\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-04-24_TIME_09-49-20-AM_30593461_111907166294952_4451956408027447296_n.jpg",
            ),
            array(
                "title" => "SEMINAR ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING \"ARTIFICIAL INTELLIGENCE IS IN YOUR HAND: THE RISE OF MACHINE LEARNING\"",
                "slug" => "seminar-artificial-intelligence-and-machine-learning-artificial-intelligence-is-in-your-hand-the-rise-of-machine-learning",
                "content" => "<p>\r\nHai Codingers !!! Kabar gembira untuk kita \r\nsemua, Himpunan Mahasiswa Teknik Informatika Universitas Komputer \r\nIndonesia akan mempersembahkan&nbsp; <b>SEMINAR ARTIFICIAL INTELLIGENCE AND \r\nMACHINE LEARNING</b><br><b>\"ARTIFICIAL INTELLIGENCE IS IN YOUR HAND: THE RISE OF MACHINE LEARNING\"</b><br><br>Cocok banget nih untuk kalian yang penasaran tentang Artificial Intelligence dan Machine Learning kuyy ikutan. <br>Seminar ini akan dilaksanakan pada Waktu dan Tempat :<br>&nbsp;Sabtu , 12 Mei 2018<br>08.00 WIB - Selesai.&nbsp; Auditorium Miracle Universitas Komputer Indonesia (Lantai 4)<br><br>Pembicara :<br>Hilman Fernandus P (Lembaga Ilmu Pengetahuan Indonesia)<br>&nbsp;Hendri Karisma (SR. Research and Development Engineer )<br><br>GUEST STAR :&nbsp; SADAYA <br>Penasaran\r\n seperti apa penampilan mereka? Ayo segera daftarkan diri kalian, selain\r\n ilmu yg kalian dapat kalian akan terhibur sama aksi mereka!<br><br>Fasilitas : SEMINAR KIT<br>&nbsp;SERTIFIKAT<br>&nbsp;SNACK<br>&nbsp;DOORPRIZE&nbsp; OPEN REGISTRASI&nbsp; <br>20 April - 11 Mei 2018<br>09.00 - 15.00 (Senin - Jumat )<br>09.00 - 12.00 (Sabtu)<br><br>Tempat pendaftaran : Lorong pelataran ekonomi Unikom<br>&nbsp;Sekretariat HMIF R.4417 Unikom<br>&nbsp; <a target=\"_blank\" rel=\"nofollow\" href=\"http://himaif.unikom.ac.id/seminar\">http://himaif.unikom.ac.id/seminar</a>&nbsp; Scan barcode pada pamflet&nbsp; HTM<br>50K - Mahasiswa Unikom<br>55K - Umum<br>60K - OTS<br><br>Pembayaran ke :<br>No. Rek : 0458611667 BNI a/n Vanadia Aviandi&nbsp; Contact Person<br>Ulfa Andriyanti<br>Line : ulfaariyanti_798<br>WA : 085723557703<br><br>Anggi<br>Line : anggighee<br>WA : 083175208806<br><br>Kuota Terbatas lohh, don't miss it codingers!\r\n\r\n<br></p><br>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-05-02_TIME_09-22-24-PM_30855905_2161840793844578_3954741676395724800_n.jpg",
            ),
            array(
                "title" => "Silaturahmi HMIF itenas dan HMIF UNIKOM",
                "slug" => "silaturahmi-hmif-itenas-dan-hmif-unikom",
                "content" => "<p>\r\n\r\nTerimakasih kepada HMIF Unikom yang sudah berkunjung ke sekretariat HMIF Itenas. Semoga silaturahmi kita dapat terus terjalin. Aamiin <br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifitenas/\">#HMIFItenas</a>&nbsp;<br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifunikom/\">#hmifunikom</a>&nbsp;<br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/kampusorange/\">#kampusorange</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-05-06_TIME_04-17-39-PM_31270339_2110384355904759_5997411526619693056_n.jpg",
            ),
            array(
                "title" => "SELAMAT ULANG TAHUN HMGD KE 40",
                "slug" => "selamat-ulang-tahun-hmgd-ke-40",
                "content" => "<p>\r\n\r\n\r\n\r\n\r\n\r\nSELAMAT ULANG TAHUN HMGD KE 40 <br>Semoga selalu kompak dan jaya selalu.&nbsp;<br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifitenas/\">#HMIFItenas</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmgditenas/\">#hmgditenas</a>&nbsp;<br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/kampusorange/\">#kampusorange</a>\r\n\r\n\r\n\r\n<br><br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-05-06_TIME_04-18-07-PM_31674331_605009283190790_2823770465443512320_n.jpg",
            ),
            array(
                "title" => "HMIF BERBAGI @SEDEKAHBAJU",
                "slug" => "hmif-berbagi-sedekahbaju",
                "content" => "<p>\r\n\r\nHalo Teman-Teman<br>.<br><br>Divisi Kerohanian kembali mengadakan program HMIF Berbagi yang akan memfasilitasi akang/teteh dan teman-teman yang ingin berbagi bersama dalam bentuk pakaian layak pakai.<br><br>Pakaian tersebut dapat dikumpulkan pada box HMIF Berbagi yang ada pada sekretariat HMIF dari tanggal 3 - 7 Juli dan pada acara Rehat Sejenak pada tanggal 7 Juli nanti.<br><br>Pakaian yang terkumpul inshaallah akan kami sedekahkan kepada Panti Yatim melalui Program Sedekah Baju yang dicanangkan oleh <a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/SedekahBaju/\">@SedekahBaju</a>&nbsp;sehingga inshaallah tepat sasaran<br><br>Mari Berbagi\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-08-15_TIME_09-16-49-AM_35275899_234115734057427_35017211961671680_n.jpg",
            ),
            array(
                "title" => "[[ PENGABDIAN PADA MASYARAKAT HIMPUNAN MAHASISWA TEKNIK INFORMATIKA ITENAS]]",
                "slug" => "pengabdian-pada-masyarakat-himpunan-mahasiswa-teknik-informatika-itenas",
                "content" => "<p>\r\n\r\nHalo seluruh keluarga HMIF ITENAS&nbsp; Pengabdian pada masyarakat HMIF Itenas akan kembali hadir di tahun 2018!&nbsp;<br><br>P2M HMIF Itenas 2018 akan dilaksanakan pada :<br>.<br>JAM : 12,13,14, dan 15 Juli 2018.<br>TEMPAT : Kampung Cikaroklok, Desa Sukasenang, Kec.Banyuresmi, Kab.Garut, Jawa Barat<br><br>Yuk biar tahu acaranya gimana dan ada apa aja, persiapkan diri untuk mengikuti kegiatan P2M HMIF Itenas 2018 !! . .<br><br>MAHASISWA! IF! IF! IF!\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-08-15_TIME_09-17-28-AM_36149103_241123356673732_3822090361623281664_n.jpg",
            ),
            array(
                "title" => "[PAID PROMOTE DIES NATALIES HMIF 2018]",
                "slug" => "paid-promote-dies-natalies-hmif-2018",
                "content" => "<p>\r\n\r\nHello Guys! Mau bisnis Kalian Makin terkenal ?<br><br>Ada Kabar Gembira nihh Sekarang Dies Natalis HMIF Itenas Open Paid PRomote untuk kalian yang ingin mempromosikan ONLINE SHOP kalian dengan harga terjangkau.<br>Kami bekerja sama dengan seluruh panitia DIES NATALIS untuk mempromosikan online shop kalian di SNAPGRAM dan POST INSTAGRAM kami dengan total 60+++ Active ACCOUNT AND 50K++ FOLLOWERS !!! Pilihan Paket Yang Disediakan Yaitu :<br>Paket I : 10K (1x Post Keep 1 day)<br>Paket II : 15K (1x Post Keep 2 day)<br>Paket III : 25K (1x Post &amp; 1 Snapgram Keep One Day)<br>Paket IV : 30K (1x Post &amp; 2 Snapgram Keep Two Days)<br>Paket V : 35K (1x Post &amp; 3 Snapgram Keep Three Days)<br><br>Untuk Post Max Foto 3 Yaa guyss !! Tunggu Apa lagi? Ayo Hubungi CP !<br>(line): zulfikrimirza1<br><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/paidpromote/\">#paidpromote</a>&nbsp;<a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/paidpromotebandung/\">#paidpromotebandung</a><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/paidpromotemurah/\">#paidpromotemurah</a>&nbsp;<a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/openpaidpromote/\">#openpaidpromote</a><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/endorse/\">#endorse</a>&nbsp;<a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/endorsemurah/\">#endorsemurah</a>&nbsp;<a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/promosiolshop/\">#promosiolshop</a><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/jasapaidpromote/\">#jasapaidpromote</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-08-15_TIME_09-17-56-AM_37742865_243065286322643_2234328732833677312_n.jpg",
            ),
            array(
                "title" => "[Penggalangan Dana Gempa Lombok]",
                "slug" => "penggalangan-dana-gempa-lombok",
                "content" => "<p>\r\n\r\nInnalillahiwainnaillahirojiun <br>Gempa terjadi di lombok utara dengan kekuatan 7Sr pada tanggal 5 Agustus 2018 dan menurut data terakhir ada 91 orang yang meninggal dunia dan 209 orang luka-luka.<br><br>Mari kita doakan kepada saudara saudara kita yang terkena dampak bencana ini, Semoga apa yang terjadi dapat menguatkan kembali para korban gempa lombok , dan untuk korban meninggal semoga amal dan ibadahnya diterima disisi-Nya dan diampuni segala dosanya. Aamiin.<br><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/hmifitenas/\">@hmifitenas</a>&nbsp;bekerja sama dengan <a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/ldk_kmitenas/\">@ldk_kmitenas</a>&nbsp;siap menyalurkan bantuan donasi yang diberikan ke korban gempa di lombok, NTB.<br>Donasi dapat di transfer melalui rekening : <br>BNI - 0395981286 <br>a.n Bachtiar Iskandar<br><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/itenas/\">#Itenas</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifitenas/\">#HMIFItenas</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-08-15_TIME_09-18-20-AM_38162651_449372278895300_940186633360113664_n.jpg",
            ),
            array(
                "title" => "MOBILE LEGENDS TOURNAMENT",
                "slug" => "mobile-legends-tournament",
                "content" => "<p>\r\n\r\nPENDAFTARAN DIPERPANJANG!!! . •MOBILE LEGENDS TOURNAMENT•<br><br>Hobi main Mobile Legends? Yuk segera daftarkan tim kamu di \"Mobile Legends Tournament\" dan raih kesempatan memenangkan total hadiah sebesar Rp 1.000.000++.<br>Catat tanggal-tanggal penting nya!! Pendaftaran di Perpanjang sampai : 12 September 2018<br>Battle Day : 15, 17, 18 September 2018<br>Tempat : Student Center Lt. 2 Itenas <br>Dengan biaya registrasi sebesar 75 K/Tim, kamu udah bisa daftarin tim kamu dengan maksimal 7 orang (No Multi Slot).<br>Terbuka untuk seluruh Mahasiswa Itenas.<br><br>Yukk ikutan daftar, slot tim juga ditambah menjadi 32 tim lohh, kuyy segera daftar sebelum kehabisan slot.<br><br>Syarat dan ketentuan lebih lanjut&nbsp;<br>CP :<br>- Anisa Putri : anisaputris2303 (line)<br>- Agistya Anugrah : agistyaanugrah (line)<br><br>Come and Join Us<br>\"Show Your Skill in Arena Moba Game\"<br><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/itenas/\">#Itenas</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifitenas/\">#HMIFItenas</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EDITED_EVENT2018-08-15_TIME_09-20-19-AM_37701699_241290843178564_5338077026697871360_n.jpg",
            ),
            array(
                "title" => "Selamat Tahun Baru Islam 1440 Hijriyah",
                "slug" => "selamat-tahun-baru-islam-1440-hijriyah",
                "content" => "<p>\r\n\r\nSelamat Tahun Baru Islam 1440 Hijriyah. Semoga kita dapat meningkatkan keimanan dan ketaqwaan di tahun baru ini.\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-10-18_TIME_02-38-01-PM_40783751_279043626044280_5215813308417970947_n.jpg",
            ),
            array(
                "title" => "[FUTSAL TOURNAMENT]  HIMPUNAN MAHASISWA TEKNIK INFORMATIKA PROUDLY PRESENT : \"IF SPORTLYMPIC FUTSAL TOURNAMENT\"",
                "slug" => "futsal-tournament-himpunan-mahasiswa-teknik-informatika-proudly-present-if-sportlympic-futsal-tournament",
                "content" => "<p>\r\n\r\nUntuk pertama kalinya HMIF Itenas mengadakan Turnamen Futsal antar jurusan se-Itenas, <br>Ayo daftar dan raih kemenanganmu!! Catet Tanggalnya&nbsp;<br>-Pendaftaran : 11 - 23 September 2018<br>- Tempat : Lapang Futsal Itenas<br>- Biaya Pendaftaran : 300k/Tim (12 Pemain &amp; 1 Official)<br>- Kick Off : 26 September 2018<br><br>Daftarkan Sekarang Juga!! Pendaftaran dan info lebih lanjut bisa menghubungi :<br>- Zulfikri Mirza<br>(line) : zulfikrimirza1 - Yugi Agus<br>(line) : yugiagusrianto\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-10-18_TIME_02-38-53-PM_40704904_2245977368982293_3612303263067877696_n.jpg",
            ),
            array(
                "title" => "[HMIF PEDULI]",
                "slug" => "hmif-peduli",
                "content" => "<p>\r\n\r\numat (28/9) malam, Badan Meteorologi, Klimatologi, dan Geofisika (BMKG) menyebut bahwa secara total ada 58 gempa susulan.<br>Gempa susulan terdiri dari 31 gempa susulan pascagempa dengan magnitudo 7,7 yang terjadi pukul 17.02 WIB, dan 27 gempa susulan setelah gempa pertama yang terjadi sekitar pukul 14.00 WIB.<br><br>Laporan sementara, terdapat beberapa korban yang meninggal karena tertimpa bangunan roboh. Tsunami juga menerjang beberapa permukiman dan bangunan yang ada di pantai.<br>------------------------------------------------------<br>.<br>HMIF dengan program <a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifpeduli/\">#HMIFPEDULI</a>-nya bermaksud untuk melakukan donasi berupa pakaian layak, buku ataupun dana yang dimana sangat dibutuhkan oleh saudara-saudara kita di Donggala, Palu dan Sulawesi Selatan. <br>Semua donasi bisa diberikan langsung dengan cara datang ke sekretariat HMIF, untuk donasi dana bisa juga transfer ke :<br>0394-5806-26 (Rek. BNI) a.n Audhiya Putri<br><br>Untuk informasi selengkapnya, bisa menghubungi kontak, Emir Hamzah : 0898-5025-509 (Narahubung)<br><br>Mari doakan, semoga saudara-saudara kita tetap aman disana. Ditemukan keluarga-keluarganya dan bagi korban yang meninggal mendapatkan tempat di sisi-Nya Amin&nbsp;<a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifitenas/\">#hmifitenas</a><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/itenasbandung/\">#itenasbandung</a>&nbsp;<a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifpeduli/\">#hmifpeduli</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-10-18_TIME_02-39-25-PM_41640977_318231155576519_1951492610815019876_n.jpg",
            ),
            array(
                "title" => "GRADUATION NIGHT PARTY",
                "slug" => "graduation-night-party",
                "content" => "<p>\r\n\r\nWisuda sebentar lagi! Kami ucapkan selamat kepada akang teteh yang telah berhasil mendapatkan gelar S,Kom-nya. Nah untuk merayakannya hayu kita dateng ke acara HMIF GRADUATION NIGHT PARTY.<br><br>SAVE THE DATE !!<br>Tanggal : 9 Oktober 2018<br>Jam : 18.30 - bosan<br>Tempat : Student Center lt2 <br>Acaranya udah pasti seru dan akan ada kejutan-kejutan ga terduga hihi, jadi jangan sampai kelewat ya acaranya!!&nbsp;<br>SEE YOU<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-10-18_TIME_02-39-52-PM_41722749_139011660391046_2435183287066492852_n.jpg",
            ),
            array(
                "title" => "#HackathonBandungLautanAPI2018-HMIFItenasBandung",
                "slug" => "hackathonbandunglautanapi2018-hmifitenasbandung",
                "content" => "<p>\r\n\r\nColab merupakan sebuah aplikasi yang mendukung perkembangan industri kreatif di bidang musik, platform ini berbasis web, yang bertujuan untuk mengubah cara kita membuat dan memplublikasikan musik karya kita sendiri maupun hasil kolaborasi.<br>Colab akan menghubungkan musisi-musisi yang ada di Indonesia dan Dunia untuk berkolaborasi dan bekerja sama dengan menghilangkan batasan waktu dan tempat. <br>Pada Colab seorang musisi baik profesional maupun amatir dapat memasukan karyanya yang masih membutuhkan instrumen lainya, contohnya seorang musisi membuat sebuah melodi gitar dan membutuhkan beat drum, maka musisi tersebut dapat memasukan melodinya dan mencari seorang drummer untuk<br>beat drum melalui platform colab.<br>Colab telah bekerja sama dengan Patrakomala Kota Bandung dengan menggunakan API Event yang disediakan Patrakomala. Dengan kerja sama ini Colab ingin membantu seniman-seniman lokal agar dikenal dan dapat mengisi event-event musik yang ada di kota Bandung. Semakin banyak musisi-musisi yang berkolaborasi bersama Colab maka akan semakin banyak karya musik yang dapat dijadikan event-event budaya yang ada dikota Bandung, dimana event-event yang ada di Kota Bandung merupakan daya tarik budaya utama bagi turis lokal maupun mancanegara.<br>Akulturasi budaya juga merupakan tujuan dari Colab, dengan menggunakan platform ini musisi tradisional diharapkan dapat<br>bekerja sama dengan musisi kontemporer untuk menggabungkan hasil karya mereka sehingga menghasilkan karya musik tradisional<br>yang sesuai dengan tren dan perkembangan zaman.<br><br>Colab dirancang untuk mengikuti perlombaan Hackaton Bandung Lautan Api 2018 yang diadakan di Atlantic City Hotel tanggal<br>06 - 07 Oktober 2018.<br><br>Colab dibuat oleh tim dari HMIF Itenas Bandung :<br>1. Mochamad Fahrizky Rohmana Putra (15-2016-125)<br>2. M. Alif Abhiesa Al Kautsar (15-2015-077)<br>3. Kevin Eza Rizky (15-2015-095)<br>4. Reza Fadilah Dwiputra (15-2015-097)<br><br>Jangan lupa like dan subscribe<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-10-18_TIME_02-40-33-PM_42775780_1739287669530227_1490120383746498164_n.jpg",
            ),
            array(
                "title" => "\"Sebaik-baik kalian adalah yang mempelajari Al-Qu'ran dan mengajarkannya.\" [Al-Bukhari 5027]",
                "slug" => "sebaik-baik-kalian-adalah-yang-mempelajari-al-quran-dan-mengajarkannya-al-bukhari-5027",
                "content" => "<p>\r\n\r\n\"Sebaik-baik kalian adalah yang mempelajari Al-Qu'ran dan mengajarkannya.\" [Al-Bukhari 5027]\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-10-18_TIME_02-40-54-PM_43375008_343689372844770_2044114751382995103_n.jpg",
            ),
            array(
                "title" => "[ Apresiasi ] diberikan Kepada:  ADHYAKSA PRADESTA (152015079) MUSA P (152015082) MUHAMMAD RAFLY (152015092) REZKY DIMAS (152015110) Dan warga setempat.",
                "slug" => "apresiasi-diberikan-kepada-adhyaksa-pradesta-152015079-musa-p-152015082-muhammad-rafly-152015092-rezky-dimas-152015110-dan-warga-setempat",
                "content" => "<p>\r\n\r\nAtas keberanian mengejar dan menangkap maling serta atas dedikasi memberantas curanmor di sekitar Itenas.<br><br>Alhamdulillah tidak ada yang terluka dan maling sebanyak 2 orang sudah dibawa ke pihak berwajib.<br><br>Tetap hati hati untuk semuanya. Saling menjaga demi lingkungan itenas yang aman sejahtera.<br><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/forzahmif/\">#ForzaHMIF</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifitenas/\">#HMIFitenas</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-10-18_TIME_02-41-23-PM_42182002_928663800665407_3424305660637558103_n.jpg",
            ),
            array(
                "title" => "[Study Banding Himakom IBN]",
                "slug" => "study-banding-himakom-ibn",
                "content" => "<p>\r\n\r\nHeloo gengs...&nbsp;<br>Salam Loyalitas Tanpa Batas..<br>Bagi kamu peserta acara Study Banding Himakom yang bertemakan \"RAKIT(Raising Knowladge with Technology). Jadi kita mau ingetin lagi nih gengsss Hari/Tgl: Kamis dan Jumat, 11/12 Oktober 2018<br>-Waktu : 07.00 - selesai<br>-Tempat : - NTMC Polri Jakarta<br>- Techpolitan The Brezze, BSD<br>- Universitas Komputer Indonesia, Bandung - Institut Teknologi Nasional, Bandung<br><br>HTM : Rp. 145.000-, Soo jangan lupa ikutan yaa gengs banyak ilmu yang kita bisa dapatkan lho serta pengalaman juga pastinyaa.. See you gengss <a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/himakom_ibn/\">#himakom_ibn</a>&nbsp;<a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/salamloyalitastanpabatas/\">#salamloyalitastanpabatas</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-10-18_TIME_02-42-10-PM_42308938_2103531253309665_7681667320176466935_n.jpg",
            ),
            array(
                "title" => "[HMIF JUARA]",
                "slug" => "hmif-juara",
                "content" => "<p>\r\n\r\nAlhamdulillah,kabar membanggakan dari HMIF<br><br>Maruli Ibrahim Batara Daulay mahasiswa jurusan Teknik Informatika berhasil meraih Medali Emas<br>kategori Kyorugi Senior Under 80Kg dalam Turnamen Taekwondo New Pandawa 2018 antar unit Se-Jawa Barat yang diselenggarakan pada tanggal 6-7 Oktober 2018 di GOR Laga Tangkas SPORT JABAR Arcamanik Bandung.<br><br>Ayo tambah lagi emas untuk HMIF Mari berjuang dan banggakan nama baik himpunanmu&nbsp;<a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/itenas/\">#Itenas</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifitenas/\">#HMIFItenas</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/kampusoranges/\">#kampusoranges</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-10-18_TIME_02-42-41-PM_42824022_491596778010068_9140734236892850104_n.jpg",
            ),
            array(
                "title" => "HAPPY GRADUATION!!!!!",
                "slug" => "happy-graduation",
                "content" => "<p>\r\n\r\nHAPPY GRADUATION!!!!!<br>SELAMAT ATAS GELAR S.Kom nya semoga berkah dan selalu diberkahi<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2018-10-18_TIME_02-43-41-PM_42792744_426822787849247_5965404804534777659_n.jpg",
            ),
            array(
                "title" => "Study Banding",
                "slug" => "study-banding",
                "content" => "<p>\r\n\r\nAlhamdulillah telah dilaksanakan kegiatan Study Banding bersama HIMAKOM Institut Bisnis Nusantara pada <br>Jum'at, 12 Oktober 2018<br>.<br>Semoga Silaturahmi dapat terjalin kembali di kemudian hari.<br>.<br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifitenas/\">#HMIFItenas</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/kampusorange/\">#KampusOrange</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2019-02-11_TIME_10-08-11-AM_43779607_244609376207194_1558240810394153819_n.jpg",
            ),
            array(
                "title" => "Mari Ber-tahsin",
                "slug" => "mari-ber-tahsin",
                "content" => "<p>\r\n\r\nHARI INI!!!!<br>ditunggu kepada rekan rekan di lab multimedia gd2 itenas????\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2019-02-11_TIME_10-09-14-AM_44000070_313052446192902_3429201188599924019_n.jpg",
            ),
            array(
                "title" => "SELAMAT HARI SUMPAH PEMUDA",
                "slug" => "selamat-hari-sumpah-pemuda",
                "content" => "<p>\r\n\r\nKita jangan mewarisi abunya sumpah pemuda tapi kita harus mewarisi apinya sumpa pemuda. ~ Ir Soekarno<br><br>Selamat Hari Sumpah Pemuda 28 Oktober 2018. Mari kita Bersatu Membangun Bangsa dan Negara Tercinta. INDONESIA!!!????????????????\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2019-02-11_TIME_10-09-45-AM_43292766_447448139113443_4658645149370866301_n.jpg",
            ),
            array(
                "title" => "#prayforjt610",
                "slug" => "prayforjt610",
                "content" => "<p>\r\n\r\n<br>Kami segenap keluarga besar HMIF mengucapkan turut berduka cita atas kejadian jatuhnya Pesawat Lion Air JT610 <br>Semoga proses SAR dapat berjalan lancar dan cepat.<br><br>Dan teruntuk kaka kami yang menjadi salah satu korban dari jatuhnya pesawat Lion Air JT610 atas nama bang Junior Priadi (IF 2004) yang kini statusnya masih hilang, semoga seluruh korban dapat segera ditemukan dan selamat, Aamiin???????? <a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifberduka/\">#HMIFberduka</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/prayforjt610/\">#prayforjt610</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2019-02-11_TIME_10-10-04-AM_43818192_322978014924654_6556943083009741948_n.jpg",
            ),
            array(
                "title" => "HMIF JUARA",
                "slug" => "hmif-juara",
                "content" => "<p>\r\n\r\nTelah diadakannya kegiatan Silahturahmi Fakultas Teknologi Industri ITENAS , Pada :<br>Tanggal : Kamis,08 November 2018<br>Tempat : Gallery Cinde Itenas<br>Agenda : Pemaparan Pengabdian Pada Masyarakat (P2M) yang telah dilaksanakan oleh masing-masing Himpunan Mahasiwa Jurusan(HMJ) ITENAS.<br><br>Alhamdulillah, HMIF mendapat Juara 2 dari 5 HMJ yang ada di Fakultas Teknologi Industri ITENAS.<br><br>Kami ucapkan terima kasih atas kepercayaan, dukungan dan kerja sama yang baik selama ini kepada semua pihak yang terlibat dalam program kerja HMIF yaitu Pengabdian Pada Masyarakat (P2M), Semoga kami dapat memberikan ilmu dan tenaga yang lebih baik untuk masyarakat luas???????? <a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifitenas/\">#hmifitenas</a>&nbsp;<br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/itenasbandung/\">#itenasbandung</a>&nbsp;<br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifjuara/\">#hmifjuara</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/kampusorange/\">#kampusorange</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2019-02-11_TIME_10-10-28-AM_44200872_188815835362609_8274980496134741937_n.jpg",
            ),
            array(
                "title" => "Maulid Nabi Muhammad SAW",
                "slug" => "maulid-nabi-muhammad-saw",
                "content" => "<p>\r\n\r\n</p>\r\n\r\n<br>Semoga keselamatan dan ampunan tercurah untukmu,keluarga, dan seluruh pengikutmu????<br><br>Maulid Nabi Muhammad SAW<br>12 Rabi'ul Awal 1440H\r\n\r\n<p>\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2019-02-11_TIME_10-12-06-AM_41937673_207476343492257_2009794047872564204_n.jpg",
            ),
            array(
                "title" => "SEMINAR \"PEMILIHAN JALUAR KARIR PROGRAMMER DI INDUSTRI 4.0 \"",
                "slug" => "seminar-pemilihan-jaluar-karir-programmer-di-industri-40",
                "content" => "<p>\r\n\r\nTerimakasih kepada PT. MITRA KINERJA UTAMA yang bekerja sama dengan Jurusan Teknik Informatika dan HMIF Itenas, sudah menyelenggarakan Seminar \"Pilihan Jalur Karir Progammer di Industri 4.0\". Pada tanggal 14 November 2018 Dengan pembicara :<br>1. Prof. Dr.-Ing.Ir.Suhardi, S.H.,M.H.<br>2. Yohanes Adi B. Wiratmo, S.T.,M.T.<br>3. Rachmat Hariyanto, S.Si.,M.T.<br><br>Semoga ilmu yang didapat bermanfaat dan berguna untuk pemilihan karir yang lebih baik.<br><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifitenas/\">#HMIFItenas</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/itenasbandung/\">#ItenasBandung</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2019-02-11_TIME_10-12-58-AM_45496005_350250055778028_8393322504852168999_n.jpg",
            ),
            array(
                "title" => "Open Stage Special Anniversary BDVon7",
                "slug" => "open-stage-special-anniversary-bdvon7",
                "content" => "<p>\r\n\r\nDalam rangka memperingati hari jadi BDV yang ke-7 , BDV menyelenggarakan kegiatan Open Stage Special Anniversary BDV on7. <br>Salah satu rangkaian dari kegiatan ini adalah Diskusi Panel yang bertema \"Sexy Startup For Investor\". Melalui kegiatan ini kami bermaksud menginspirasi para peserta yang memiliki keinginan mendirikan sebuah startup namun terkendala oleh modal. <br>Kegiatan ini ingin membuka pandangan bahwa sebuah startup yang tidak memiliki modal dapat berkembang, salah satunya melalui suntikan dana dari Investor. <br>Namun sayangnya ketatnya persaingan dan dunia startup yang terus berkembang membuat investasi yang diperoleh tidak semudah sebelumnya. <br>Diskusi ini dimaksudkan untuk mencari tahu seberapa penting investasi baik dari sudut pandang Investor maupun startup yang sudah memiliki pengalaman berhubungan langsung dengan Investor, dan startup seperti apakah yang sangat menarik perhatian para investor atau dengan kata lain Sexy Startup For Investor. <br>Kamu berkeinginan mendirikan sebuah startup? Jika jawabannya IYA, maka acara ini dibuat memang untuk kamu. .<br><br>Yuk langsung register di bit.ly/bdvonseven dan registrasi member di member.bandungdigitalvalley.com. <br>Sampai jumpa :) More Info &amp; Follow Us <br>Instagram : telkombdv <br>twitter : telkombdv <br>Facebook : telkombdv <br>website : <a target=\"_blank\" rel=\"nofollow\" href=\"http://www.bandungdigitalvalley.com\">www.bandungdigitalvalley.com</a> .<br>.<br><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/building/\">#Building</a>&nbsp;National ICT Competitiveness<br><br>Through Colaborative Innovation#\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2019-02-11_TIME_10-13-30-AM_47096939_295894244387466_1060287345154202165_n.jpg",
            ),
            array(
                "title" => "13th DIES NATALIS HMIF",
                "slug" => "13th-dies-natalis-hmif",
                "content" => "<p>\r\n\r\nTak terasa sisa waktu tinggal sedikit lagi menuju acara yang ditunggu tunggu! <br>FUTURE IN OUR HAND!<br><br>Tempat : Villa Lagenta Lembang<br>Tanggal : 22 Desember 2018<br>Pukul : 16.00 - Selesai<br><br>Dimeriahkan oleh :<br><br>Orkes Malam Jumat<br>Gos Blues<br>Vaccinate Light<br>Band Nopan<br>Band Brewok<br>Grizzly<br><br>Untuk info terkini DIES NATALIS HMIF, stay tuned : <br>Ig : <a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/hmifitenas/\">@hmifitenas</a>&nbsp;<br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/diesnatalishmif/\">@diesnatalishmif</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2019-02-11_TIME_10-13-54-AM_46950932_435085640356250_834310462481065398_n.jpg",
            ),
            array(
                "title" => "#PRAYFORBANTEN&LAMPUNG",
                "slug" => "prayforbantenlampung",
                "content" => "<p>\r\n\r\n<br>Kami segenap keluarga HMIF ITENAS menyampikan rasa belasungkawa yang sedalam dalam nya atas musibah tsunami selat sunda.<br>Mari kita menundukan kepala berdoa untuk keselamatan dan ketabahan untuk saudara saudara kita yang sedang tertimpa musibah????<br><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifpeduli/\">#HMIFPEDULI</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/prayforbantendanlampung/\">#prayforbantendanlampung</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2019-02-11_TIME_10-14-19-AM_47460918_2282079555449076_4338090535188007715_n.jpg",
            ),
            array(
                "title" => "Selamat Hari Raya Natal",
                "slug" => "selamat-hari-raya-natal",
                "content" => "<p>\r\n\r\nHimpunan Mahasiswa Teknik Informatika Itenas mengucapkan Selamat Hari Raya Natal bagi yang merayakan<br>Semoga makin memperkuat rasa kesatuan kita semua amin ???????? <a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifitenas/\">#HMIFItenas</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2019-02-11_TIME_10-14-44-AM_47048156_374750596616033_6861914553183529634_n.jpg",
            ),
            array(
                "title" => "KUNJUNGAN INDUSTRI",
                "slug" => "kunjungan-industri",
                "content" => "<p>\r\n\r\nSIAPKAN DIRI MU ????????<br>Hallo mahasiswa teknik yang keren abis. Eitts belum lengkap rasanya kalau ngaku sebagai mahasiswa teknik tapi belum pernah mengunjungi ranah Industri yang tentunya berasa banget atmosfer lingkungan kerja para engineer.<br><br>Nah tenang gaesss, kita dari Mahasiswa Teknik Informatika Itenas akan mengadakan “Study Visit ke Bali” dalam rangka Kunjungan Industri. <br>Catet Tanggalnya!!<br>???? : 13-20 Januari 2019<br>???? : Kampus Itenas Bandung<br><br>Dont Miss it gaess, kapan lagi bisa wisata sambil bisa tahu dunia industri ????????\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2019-02-11_TIME_10-15-20-AM_47694087_2031437030489845_7245692282420461053_n.jpg",
            ),
            array(
                "title" => "Musyawarah Besar",
                "slug" => "musyawarah-besar",
                "content" => "<p>\r\n\r\nBerikut adalah info mengenai pelaksanaan Mubes HMIF 2019, yang akan di laksanakan pada :<br>Tanggal: Selasa, 29 Januari 2019 - Jum'at, 1 Februari 2019<br>Waktu: 08.00 - Selesai<br>Tempat : Perpustakaan lt.3 / Ruang 9301<br>.<br><br>mari luangkan waktunya demi HMIF yang lebih baik.<br>.<br>Terimakasih\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2019-02-11_TIME_10-16-04-AM_49907248_743374716047809_4191119957298412089_n.jpg",
            ),
            array(
                "title" => "HMIF PROUDLY PRESENT",
                "slug" => "hmif-proudly-present",
                "content" => "<p>\r\n\r\nHMIF PROUDLY PRESENT :<br>.<br><br>MAKRAB 2018 <br>METHAPORIA “Berubah lebih baik dengan keceriaan” <br>Hallo teman teman! <br>Ayo datang dan ramaikan di acara MAKRAB HMIF 2018.<br><br>Place : Student Center ITENAS 2nd Floor<br>Date : 12 Februari 2019 <br>Time : 04.00 pm - 09.30 pm <br>Dimeriahkan dengan :<br>- Band Performance<br>- Games<br><br>For the info , stay tune! : <br>LINE : inu_wissnu<br>See you there\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2019-02-11_TIME_10-16-47-AM_51179636_836982143321406_7057808592264148300_n.jpg",
            ),
            array(
                "title" => "RANGKAIAN MUSYAWARAH BESAR HMIF 2017/2018",
                "slug" => "rangkaian-musyawarah-besar-hmif-20172018",
                "content" => "<p>\r\n\r\nAlhamdulillah telah dilaksanakan rangkaian musyawarah besar HMIF 2017/2018 yang berlangsung pada:<br>Tanggal: 29, 30, dan 31 Januari 2019.<br>Lokasi: Ruang 9301, Gedung 9.<br>Agenda inti: - Pembacaan LPJ BP.<br>- Pembacaan LPJ BPA.<br>- Simbolis Serah Terima Jabatan kepada Penanggung Jawab Sementara.<br>- Penyematan Jaket HMIF.<br>- Pembahasan AD/ART.<br>- Pembahasan GBHO.<br>- Pengenalan Calon Ketua HMIF periode 2018/2019<br>- Pengenalan Calon Ketua BPA HMIF periode 2018/2019<br>- Dan agenda tambahan.<br><br>Rangkaian acara selanjutnya adalah Serah Terima Jabatan kepada Kepengurusan Baru HMIF 2018/2019.<br><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/demisioner/\">#Demisioner</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/teknikinformatika/\">#TeknikInformatika</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/forzahmif/\">#ForzaHMIF</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifitenas/\">#HMIFITENAS</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmif/\">#HMIF</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2019-02-11_TIME_10-17-49-AM_52087667_119377829132377_5438771216573904040_n.jpg",
            ),
            array(
                "title" => "Pendaftaran Peningkatan Kualitas Keorganisasian Mahasiswa (PKKM) HMIF 2019",
                "slug" => "pendaftaran-peningkatan-kualitas-keorganisasian-mahasiswa-pkkm-hmif-2019",
                "content" => "<p>Assallamu'alaikum wr.wb<br></p><p><br>Dengan adanya Peningkatan Kualitas Keorganisasian Mahasiswa (PKKM) 2019, maka Himpunan Mahasiswa Teknik Informatika (HMIF) Itenas membuka pendaftaran untuk bergabung bersama Himpunan Mahasiswa Teknik Informatika Itenas.<br><br>Pendaftaran dibuka mulai  tanggal 28 September 2019 sampai 1 Oktober 2019.<br>Persyaratan dan ketentuan belaku. <br><br>Tata cara pendaftaran :<br>1. Buka website HMIF&nbsp;<a href=\"http://hmif.itenas.ac.id/\" target=\"_blank\" rel=\"nofollow\">http://hmif.itenas.ac.id/</a> <br>2. Buka <a href=\"https://bit.ly/2obdfE1\" target=\"_blank\" rel=\"nofollow\">https://bit.ly/2obdfE1</a> , kemudian download <br>&nbsp; &nbsp; - Surat pernyataan <br>&nbsp; &nbsp; - Surat izin orangtua<br>3. Semua surat yang sudah didownload dan sudah dilengkapi harap di scan dengan format .pdf atau .jpg. Hasil scan tersebut digunakan untuk melengkapi syarat pendaftaran pada google form.<br>4. Kemudian daftarkan identitas diri dengan cara membuka link&nbsp;<a href=\"http://bit.ly/pkkm2019hmif\" target=\"_blank\" rel=\"nofollow\">http://bit.ly/pkkm2019hmif</a>&nbsp;<br><br>Let's come join us!!!<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EDITED_EVENT2019-09-28_TIME_11-35-06-PM_PKKM.jpg",
            ),
            array(
                "title" => "Lomba Gemastik XIII Kementerian Pendidikan Dan Kebudayaan",
                "slug" => "lomba-gemastik-xiii-kementerian-pendidikan-dan-kebudayaan",
                "content" => "<p><b>[DIVISI AKADEMIK HMIF]</b><br><br></p><p>Halo Codinger, bidang akademik sedang mencari tim untuk mengikuti lomba Gemastik ke 13. GEMASTIK atau Pagelaran Mahasiswa Nasional Bidang Teknologi Informasi dan Komunikasi, merupakan program Pusat Prestasi Nasional, Kementerian Pendidikan dan Kebudayaan. Lomba diantara lain yaitu :&nbsp;</p><p><br>Divisi I   : Pemogramman\r\n\r\n (Programming)<br>Divisi II  : Keamanan Siber \r\n\r\n (Cyber Security)<br>Divisi III : Penambangan Data\r\n\r\n (Data Mining)\r\n\r\n<br>Divisi IV  : Desain Pengalaman Pengguna (UX Design)<br>Divisi V   : Animasi (Animation)<br>Divisi VI  : Kota Cerdas (Smart City)<br>Divisi VII : Karya Tulis Ilmiah TIK (ICT Scientific Paper)<br>Divisi VIII: Pengembangan Perangkat Lunak (Software Development)<br>Divisi IX  : Piranti Cerdas, Sistem Benam &amp; IoT (Smart Device, Embedded System &amp; IoT)<br>Divisi X   : Pengembangan Aplikasi Permainan (Game Development)<br>Divisi XI  : Pengembangan Bisnis TIK (ICT Business Development)<br><br>Info lebih lanjut di website :&nbsp;\r\n\r\n<a target=\"_blank\" rel=\"nofollow\" href=\"https://gemastik13.telkomuniversity.ac.id/\">https://gemastik13.telkomuniversity.ac.id/</a>&nbsp;\r\n</p><p>Download info&nbsp;petunjuk&nbsp;lomba&nbsp;:&nbsp;<a target=\"_blank\" rel=\"nofollow\" href=\"https://cdn-gemastik13.telkomuniversity.ac.id/Petunjuk_Gemastik_13.pdf\">https://cdn-gemastik13.telkomuniversity.ac.id/Petunjuk_Gemastik_13.pdf</a><br></p><p>Pendaftaran : 23 Juli - 7 Agustus 2020.</p><p>Untuk&nbsp;informasi&nbsp;dan&nbsp;pendataan&nbsp;tim&nbsp;dari itenas&nbsp;bisa&nbsp;hubungi<br>CP : Alhimny Dwinata Utama ( Whatsapp 087825351290).<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EDITED_EVENT2020-07-30_TIME_09-27-52-PM_Gemastik12-Logo-default.png",
            ),
            array(
                "title" => "HMIF CODING COMPETITION UI/UX DESIGN 2020",
                "slug" => "hmif-coding-competition-uiux-design-2020",
                "content" => "<p>[KHUSUS PELAJAR SMA/SMK SE-DERAJAT &amp; MAHASISWA]<br></p><p><br>Halo<br>Program Studi Informatika ITENAS membuka kesempatan lho bagi kalian yang suka membuat design user interface Android/Desktop/Web untuk bergabung dalam UI/UX Design Competition 2020 dengan total hadiah jutaan rupiah<br><br>Apa aja sih kak syarat dan ketentuan untuk ikut kompetisi ini? Dan gimana ya kak cara ikutan kompetisinya? Semuanya udah tertera di poster ya.<br><br>Untuk informasi lebih lanjut kalian bisa langsung kontak ke nomer dibawah ini ya!<br>Rian : 081573717637 (WA)<br>Ruth : 082321378690 (WA)<br><br>Yuk buruan ikutan, Semoga kamu pemenangnya ya!<br><br>#UI/UXDESIGNCOMPETITION2020<br>#INFORMATIKA<br>#ITENAS<br></p><p><br></p><p>Link Pendaftaran&nbsp;Peserta :&nbsp;<a target=\"_blank\" rel=\"nofollow\" href=\"https://forms.gle/abx6HM5FZ1UMH62H7\">https://forms.gle/abx6HM5FZ1UMH62H7</a></p><p>Video Panduan Perlombaan :\r\n\r\n<br></p><p>\r\n\r\n</p><p><a target=\"_blank\" rel=\"nofollow\" href=\"https://drive.google.com/file/d/1kwWrqW_VavUFOQQMXmDbpV1zX43J84B9/view?usp=sharing\">https://drive.google.com/file/d/1kwWrqW_VavUFOQQMXmDbpV1zX43J84B9/view?usp=sharing</a><br></p><p></p><p><a target=\"_blank\" rel=\"nofollow\" href=\"https://drive.google.com/file/d/1Hl_y-qS0ja0jx4fPnqrBTwMxpuhM0j3r/view?usp=sharing\"></a></p><p><a target=\"_blank\" rel=\"nofollow\" href=\"https://drive.google.com/file/d/1Hl_y-qS0ja0jx4fPnqrBTwMxpuhM0j3r/view?usp=sharing\">Download Panduan &amp; Ketentuan Peserta : </a></p><p><a target=\"_blank\" rel=\"nofollow\" href=\"https://drive.google.com/file/d/1Hl_y-qS0ja0jx4fPnqrBTwMxpuhM0j3r/view?usp=sharing\">https://drive.google.com/file/d/1Hl_y-qS0ja0jx4fPnqrBTwMxpuhM0j3r/view?usp=sharing</a></p>\r\n\r\n<br><p></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EDITED_EVENT2020-11-07_TIME_07-45-20-AM_POSTER_CODING_COMPETITION_REVISI_(1).jpg",
            ),
            array(
                "title" => "WEBINAR SERIES PART 1",
                "slug" => "webinar-series-part-1",
                "content" => "<p>\r\n\r\nHello Folks,<br><br>Mari ikuti Webinar Series Part 1 yang berjudul \"Adaptation of learning during a pandemic\" yang diadakan oleh Himpunan Mahasiswa Teknik Informatika ITENAS.<br><br>Dengan pembicara :<br>Lisa Kristiana, S.T., M.T., Ph.D.<br>Dapatkan pengetahuan dan wawasan baru dalam webinar yang akan di selenggarakan pada :<br>???? Hari, Tanggal : Minggu, 11 Oktober 2020<br>? Waktu : 13.00 WIB - selesai.<br>???? Tempat : ZOOM<br>???? HTM : 20K<br><br>Ayo daftarkan diri kamu!<br>????<a target=\"_blank\" rel=\"nofollow\" href=\"http://bit.ly/Webinar-HMIF-1\">http://bit.ly/Webinar-HMIF-1</a><br>????<a target=\"_blank\" rel=\"nofollow\" href=\"http://bit.ly/Webinar-HMIF-1\">http://bit.ly/Webinar-HMIF-1</a><br>????<a target=\"_blank\" rel=\"nofollow\" href=\"http://bit.ly/Webinar-HMIF-1\">http://bit.ly/Webinar-HMIF-1</a><br><br>Terakhir pendaftaran : 9 Oktober 2020<br><br>Jangan sampai ketinggalan ya! Setiap pendaftar akan mendapatkan E-Certificate.<br><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/itenas/\">#Itenas</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifitenas/\">#HMIFItenas</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2021-02-02_TIME_09-36-12-PM_ss.jpg",
            ),
            array(
                "title" => "WEBINAR SERIES PART 2",
                "slug" => "webinar-series-part-2",
                "content" => "<p>\r\n\r\nHalo semuanya!<br><br>Ayo kembali ikuti Webinar Series Part 2 yang berjudul \"Self Development and Possibilities During Pandemic\" yang diadakan oleh Himpunan Mahasiswa Teknik Informatika ITENAS.<br><br>Dengan pembicara :<br>Bani Adil, Content Creator and Editor Tim2One Production by <a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/chandraliow/\">@chandraliow</a><br>Dapatkan pengetahuan dan wawasan baru dalam webinar yang akan di selenggarakan pada :<br>???? Hari, Tanggal : Minggu, 15 November 2020<br>? Waktu : 13.00 WIB - selesai.<br>???? Tempat : ZOOM<br>???? HTM : 25K<br><br>Ayo daftarkan diri kamu segera!<br>????<a target=\"_blank\" rel=\"nofollow\" href=\"http://bit.ly/WbSeries2\">http://bit.ly/WbSeries2</a><br>????<a target=\"_blank\" rel=\"nofollow\" href=\"http://bit.ly/WbSeries2\">http://bit.ly/WbSeries2</a><br>????<a target=\"_blank\" rel=\"nofollow\" href=\"http://bit.ly/WbSeries2\">http://bit.ly/WbSeries2</a><br><br>Jangan sampai ketinggalan ya!<br>Penutupan pendaftaran : 13 November 2020<br>Setiap pendaftar akan mendapatkan E-Certificate.\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2021-02-02_TIME_09-37-45-PM_ss2.jpg",
            ),
            array(
                "title" => "PENINGKATAN KUALITAS KEORGANISASIAN MAHASISWA 2020",
                "slug" => "peningkatan-kualitas-keorganisasian-mahasiswa-2020",
                "content" => "<p>\r\n\r\nAssalamualaikum wr wb<br>Hallo selamat siang teman teman , Bagi kalian yang ingin tau tentang Organisasi Kampus, dan berminat menambah wawasan tentang Dunia Kerja serta pengalaman ber-organisasi, Himpunan Mahasiswa Teknik Informatika membuka pendaftaran untuk anggota baru periode 2020 yang ingin bergabung bersama kami?<br><br>Pendaftaran :<br>12 November 2020 - 18 November 2020<br><br>Untuk info lebih lanjut akan dijelaskan pada pertemuan di gmeet pada tanggal 11 November 2020?????<br><br>Contact Person ( Yuan ) :<br>087825675766 ( Whatsapp)<br>myuanr ( Line )<br><br>Wassalamu'alaikum Wr. Wb.\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2021-02-02_TIME_09-38-46-PM_ss4.jpg",
            ),
            array(
                "title" => "HMIF PEDULI - OPEN DONATION - Bakti Sosial Panti Yatim Indonesia 2020",
                "slug" => "hmif-peduli-open-donation-bakti-sosial-panti-yatim-indonesia-2020",
                "content" => "<p>\r\n\r\nAssalamu'alaikum Wr. Wb..<br>Teman-teman akang teteh semua, mari kita bersama membantu dan berbagi kebahagiaan kepada Panti Yatim yang mengalami masa sulit dalam pandemi COVID-19 ini.<br>.<br>Donasi akan kita salurkan kepada Panti Yatim Indonesia di Cikutra Barat.<br>.<br>Donasi dalam bentuk uang, buku bacaan, alat tulis, sembako dan baju layak pakai dapat disalurkan melalui :<br>Langsung<br>Via transfer<br>.<br>Konfirmasi dan info lebih lanjut hubungi:<br>0823-2137-8690(Ruth)<br>0888-2399-227(Sarah)<br>.<br>????Periode donasi: 16 November 2020 - 20 November 2020<br>.<br>Berapa rupiah pun yang teman-teman akang teteh semua sisihkan, akan sangat berarti bagi saudara-saudara kita yang membutuhkan.<br>Terima kasih.<br>Wassalamu'alaikum Wr. Wb.<br>.<br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/pengabdianpadamasyarakat/\">#PengabdianPadaMasyarakat</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifitenas/\">#HMIFItenas</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/itenas/\">#Itenas</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2021-02-02_TIME_09-40-27-PM_ss3.jpg",
            ),
            array(
                "title" => "HMIF AMPLIFIER PODCAST",
                "slug" => "hmif-amplifier-podcast",
                "content" => "<p>\r\n\r\nHallo teman-teman semua!!,yang ditunggu akhirnya tiba juga ????????<br><br>Banyak dari kita yang ingin mengetahui berbagai macam hal dari seseorang, namun sering kali terkendala banyak hal.<br>Salah satu cara untuk mengetahui berbagai macam hal adalah dengan cara komunikasi dua arah atau \"Ngobrol\". ??<br>Di era digital ini ngobrol telah dikemas menjadi suatu hal yang menarik yang dinamakan \"Podcast\".<br>Nahh kali ini HMIF akan memperkenalkan program baru yang bernama \"AMPLIFIER\".??<br>Program ini berisi podcast bersama rekan rekan HMIF dengan pembahasan topik topik menarik.<br><br>Pada HMIF AMPLIFIER kali ini narasumber yang diajak berbincang adalah \"M FAHRIZKY PUTRA\" alumni angkatan 2016 dengan pembahasan \"INVESTASI WAKTU\"????????<br><br>????Untuk selengkapnya cek link berikut:<br><a target=\"_blank\" rel=\"nofollow\" href=\"https://open.spotify.com/episode/3AMi1WBYO8fvu7O1IQvjrw?si=7wmrDlA8Sv6nFt9xevKYUA\">https://open.spotify.com/episode/3AMi1WBYO8fvu7O1IQvjrw?si=7wmrDlA8Sv6nFt9xevKYUA</a><br><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/itenas/\">#Itenas</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifitenas/\">#HMIFItenas</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/amplifier/\">#Amplifier</a>.\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2021-02-02_TIME_09-41-49-PM_ss5.jpg",
            ),
            array(
                "title" => "IF – SPORT 2020 Present : [VALORANT ONLINE TURNAMENT]",
                "slug" => "if-sport-2020-present-valorant-online-turnament",
                "content" => "<p>\r\n\r\nHi guyss ! segera daftarkan tim kamu di VALORANT ONLINE TURNAMENT yang diadakan oleh HMIF !<br><br>Catat tanggal-tanggal penting nya yaa !<br>Open Regist : 14 Desember 2020 - 24 Januari 2021<br>Battle Day : 25 - 30 Januari 2021<br>Tempat : Rumah masing - masing<br><br>Biaya registrasi: Rp. 50.000/Tim,<br>Jumlah player: maksimal 7 player<br>NO MULTI-SLOT.<br>TERBUKA UNTUK SELURUH MAHASISWA DAN ALUMNI IF DAN IS ITENAS nihh.<br><br>Ayoo Daftarkan sekarang juga! Segera daftar sebelum kehabisan slot.<br><br>Syarat dan ketentuan lebih lanjut ????<br>CP :<br>- Try Novriyanto : 081 241 697 329 (WhatsApp)\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2021-02-02_TIME_09-43-26-PM_ss6.jpg",
            ),
            array(
                "title" => "Webinar Prospek dan Profesi Kerja Informatika",
                "slug" => "webinar-prospek-dan-profesi-kerja-informatika",
                "content" => "<p>\r\n\r\nHallo Temen - Temen Mahasiswa!!<br><br>Ingin tahu lebih dalam mengenal prospek dan peluang kerja pada bidang Informatika?<br>Mari ikuti Webinar Prospek dan Profesi Kerja Informatika dengan tema \"Prospek dan Peluang Kerja Pada Bidang Industri Video Game\".<br><br>?????Dengan pembicara :<br>Nadya Octavia (Alumni Informatika Itenas 2006)<br>berkerja sebagai Lead Game Designer di PT. Nightspade Multi Kreasi<br><br>Acara ini akan diselenggarakan pada:<br>???? Hari, Tanggal : Selasa, 22 Desember 2020<br>? Waktu : 19.00 WIB - selesai.<br>???? Tempat : Virtual Converence Zoom Meeting<br><br>?Pendaftaran Gratis mendapatkan ilmu bermanfaat &amp; E-Sertifikat?<br><br>Yuk, tunggu apa lagi? daftarkan diri anda sekarang juga!<br>???? bit.ly/Daftar-Webinar-Prospek-Kerja-IF<br><br>Info lebih lanjut hubungi:<br>????WA : 088222071681 (Nafia)<br><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/itenas/\">#Itenas</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifitenas/\">#HMIFItenas</a>\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2021-02-02_TIME_09-44-53-PM_ss7.jpg",
            ),
            array(
                "title" => "WEBINAR SERIES PART 3",
                "slug" => "webinar-series-part-3",
                "content" => "<p>\r\n\r\nHalo semuanya!<br><br>Ayo kembali ikuti Webinar Series Part 3 yang berjudul \"The Way Of Success\" yang diadakan oleh Himpunan Mahasiswa Teknik Informatika ITENAS.<br>Akan ada materi \"Menjadi Lulusan IT Masa Kini dan Peluang Kerja\" yang dibawakan oleh narasumber.<br><br>Dengan pembicara :<br>Galih Pratama, COO BuildWith Angga<br>Dapatkan pengetahuan dan wawasan baru dalam webinar yang akan di selenggarakan pada :<br>???? Hari, Tanggal : Minggu, 27 Desember 2020<br>? Waktu : 13.00 WIB - selesai.<br>???? Tempat : ZOOM<br>???? HTM : FREE<br><br>Ayo daftarkan diri kamu segera!<br>????<a target=\"_blank\" rel=\"nofollow\" href=\"http://bit.ly/WbSeries3\">http://bit.ly/WbSeries3</a><br>????<a target=\"_blank\" rel=\"nofollow\" href=\"http://bit.ly/WbSeries3\">http://bit.ly/WbSeries3</a><br>????<a target=\"_blank\" rel=\"nofollow\" href=\"http://bit.ly/WbSeries3\">http://bit.ly/WbSeries3</a><br><br>Jangan sampai ketinggalan ya!<br>Setiap pendaftar akan mendapatkan E-Certificate.<br>Akan ada hadiah menarik loh, voucher kelas online dari build with angga.\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2021-02-02_TIME_09-46-37-PM_ss8.jpg",
            ),
            array(
                "title" => "HMIF AMPLIFIER",
                "slug" => "hmif-amplifier",
                "content" => "<p>\r\n\r\nHallo teman-teman! Podcast Amplifier kembali lagiii!????????<br><br>Kali ini kita ngobrol-ngobrol seru bareng “FUAD HASAN” alumni angkatan 15 yang pernah menjabat sebagai Kahim juga lhoo!?<br>HMIF AMPLIFIER kali ini bertemakan “PASSION TO BUSSINESS”????????<br><br>????Untuk selengkapnya cek link berikut:<br><a target=\"_blank\" rel=\"nofollow\" href=\"https://open.spotify.com/episode/7z9T5OiyNJESuThiQrtUHI?si=IYbRdm4dTnGwK9Oz6l99NQ\">https://open.spotify.com/episode/7z9T5OiyNJESuThiQrtUHI?si=IYbRdm4dTnGwK9Oz6l99NQ</a><br><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/itenas/\">#Itenas</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/hmifitenas/\">#HMIFItenas</a><br><a target=\"_blank\" rel=\"nofollow\" href=\"https://www.instagram.com/explore/tags/amplifier/\">#Amplifier</a>.\r\n\r\n<br></p>",
                "category_id" => 1,
                "user_id" => 1,
                "status" => 1,
                "banner" => "EVENT_2021-02-02_TIME_09-47-37-PM_ss9.jpg",
            ),
        );

        \App\Post::insert($posts);
    }
}
